config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "application#welcome"

  get '/signup',  to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy'

  get '/auth/facebook/callback', to: 'sessions#oauth'
  post '/users/:id/trips/new', to: 'trips#create'

  get '/trips/:id/detail', to: 'trips#detail'

  resources :users do
    resources :trips
  end

  resources :trips do
      resources :places
  end

  resources :places do
    resources :comments
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
     @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :place
end

app/models/place.rb
class Place < ActiveRecord::Base
  belongs_to :trip
  has_many :comments
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  belongs_to :user
  has_many :places

  default_scope -> { order(id: :asc)}

  def places_attributes=(places_attributes)
    places_attributes.values.each do |places_attributes|
      self.places.build(places_attributes)
    end
  end


  def next
      trips = trip_id_by_name
      trip_index = trips.find_index(id)
      next_trip = trip_index + 1
      if next_trip < trips.length
        trips[next_trip]
      else
        id
      end
    end

    def previous
      trips = trip_id_by_name
      trip_index = trips.find_index(id)
      previous_trip = trip_index - 1
      if previous_trip < trips.length
        trips[previous_trip]
      else
        id
      end
    end

  private

  def trip_id_by_name
    @trip_id ||= Trip.order(name: :asc).pluck(:id)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :places, through: :trips
  has_many :trips
  validates :username, presence: true, length: { minimum: 5 }, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
  has_secure_password validations: false

  def self.number_of_trips
    self.all.sort_by {|user| user.trips.size * -1}
  end

  def self.find_or_create_by_omniauth(auth_hash)
    where(email: auth_hash[:info][:email]).first_or_create do |user|
      user.username = auth_hash[:info][:username]
      user.username = auth_hash[:info][:name]
      user.password = SecureRandom.hex
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method [:current_user, :logged_in?]


  private

  def current_user
      if session[:user_id]
        @current_user ||= User.find(session[:user_id])
      else
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session[:user_id] = nil
    redirect_to '/', notice: 'You are logged out!'
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_place

  def index
    @comments = @place.comments
    respond_to do |format|
      format.html { render 'index.html', :layout => false }
      format.json { render json: @comments }
     end
  end

  def create
    @comment = @place.comments.build(comments_params)
    if @comment.save
        # render 'comments/show', :layout => false
        render json: @comment
    end
  end

  private

  def set_place
    @place = Place.find(params[:place_id])
  end

  def comments_params
    params.require(:comment).permit(:name, :description)
  end
end

app/controllers/places_controller.rb
require 'pry'
class PlacesController < ApplicationController

  def index
    @places = Place.all
  end

  def new
    @place = Place.new(trip_id: params[:trip_id])
  end

  def create
    @place = Place.new(place_params)
    if @place.save
      flash[:success] = "Added one adventure!"
      redirect_to trip_place_path(:trip_id, @place)
    else
      render :new
    end
  end

  def edit
    @place = Place.find(params[:id])
  end

  def show
    @place = Place.find(params[:id])
    @comments = @place.comments
    @comment = @place.comments.build
  end

  def update
    @place = Place.find(params[:id])
    @place.update(place_params)
    redirect_to trip_place_path(@place)
  end

  def destroy
    @place = Place.find(params[:id])
    @place.destroy
    redirect_to user_path(current_user)
  end

  private

  def place_params
    params.require(:place).permit(:name, :memory, :user_id, :trip_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    if logged_in?
      redirect_to user_path(current_user)
    else
      @user = User.new
    end
  end

  def create
    validate_login
  end

  def oauth
    @user = User.find_or_create_by(uid: auth['uid']) do |u|
         u.username = auth['info']['name']
         u.email = auth['info']['email']
         u.image = auth['info']['image']
         u.password = SecureRandom.hex
       end

      session[:user_id] = @user.id
      render 'application/welcome'
     end

     def destroy
       log_out
     end

  protected

  def auth
    request.env['omniauth.auth']
  end

  private

  def session_params
    params.require(:user).permit(:username, :password_confirmation, :uid, :password)
  end

  def validate_login
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      redirect_to user
    else
    flash.now[:danger] = 'Invalid username/password. Try again.'
    render :new
    end
  end

end

app/controllers/trips_controller.rb
require 'pry'

class TripsController < ApplicationController

  def index
    @trips = Trip.all
  end

  def new
    @trip = Trip.new
    @trip.places.build
  end

  def detail
    @trip = Trip.find(params[:id])
    render plain: @trip.places.name
  end

  def create
    @trip = current_user.trips.new(trip_params)
    if @trip.save
     flash[:success] = "You've added a new trip!"
     redirect_to user_trip_path(current_user, @trip)
    else
     render :new
    end
  end

  def show
    @trip = Trip.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @trip }
    end
  end

  def edit
    @trip = Trip.find(params[:id])

  end

  def update
    @trip = Trip.find(params[:id])
    if @trip.update(trip_params)
      flash[:success] = "Trip updated!"
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy
    flash[:success] = "Trip deleted"
    redirect_to user_path(current_user)
  end

  private

  def trip_params
    params.require(:trip).permit(:name, :date, :user_id, :places_attributes => {})
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def index
    @users = User.all
    @users = User.number_of_trips

  end

  def new
    if logged_in?
      redirect_to user_path(current_user)
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to user_path(@user)
    else
      flash[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    if @user
      @user.session.destroy
    end
  end

  private

    def user_params
      params.require(:user).permit(:username, :email, :password, :password_comfirmation, :uid)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end
end

app/views/application/welcome.html.erb
<!DOCTYPE html>
  <html>
    <head>
      <style>
      html {color: white;
            font-family: "Impact";
            letter-spacing: 3px;
            font-size: 1.2em;
          }
      h1 {font-size: 3em}
      body {background-size: cover;
            background-repeat: no-repeat;
            background-attachment: fixed;}
      a { color: white}
      .login {background-color: black;
              background: rgba(0, 0, 0, 0.7);
              margin-top: 350px;
              padding-top: 5px;
              padding-bottom: 5px;
              width: 100%;
              }
       a:hover {font-size: 1.1em}
      </style>
    </head>
    <body background= "https://edge.alluremedia.com.au/m/g/2016/01/rio-de-janeiro-sunset.jpg">
    <center><h1>TRAVLR.</h1>
      <center><h2>Track your Adventures, Share your Story.</h2>

    <div class= "login">

     <h3><%= link_to "LOG IN", sessions_new_path %></h3>
         <% if session[:user_id] %>
           <h2><%= @user.username %></h2>
           <img src="<%= @user.image %>"><br>
           <br>
           <%= link_to "Enter", user_path(current_user) %>
         <% else %>
           <%= link_to('Log in with Facebook!', '/auth/facebook') %>
         <% end %>
      <p>Don't have an account? <%= link_to "SIGN UP", signup_path %></p>
    </div>
  </body>
</html>

app/views/comments/index.html.erb
<ul>
  <% @comments.each do |comment| %>
  <li><%= comment.description %></li>
    <p>-<%= comment.name %></p>
  <% end %>
</ul>

app/views/comments/show.html.erb
<li><%= @comment.description %></li>
<li>-<%= @comment.name %></li>

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation", style="color: red;">
    <div class="alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<br>
<%= link_to "Adventure Dashboard", user_path(current_user) %> <br>
<br>
<%= link_to "Travlr's Latest Trips", trips_path %><br>
<br>
<%= link_to "Logout", logout_path %>

app/views/layouts/_header.html.erb
<head>
  <style>

  html {color: white;
        letter-spacing: 3px;
      }
  h1 {font-size: 3em;
  font-family: "Impact";
}
  body {background-image: url("https://www.visitdubai.com/-/media/optimised-images/itineraries/24%20hours%20in%20dubai/dubai-in-24-hours-panel-desktop.jpg");
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: fixed;
        line-height: 90%;
        font-size: 1.2em;
        font-family: "Optima", "Lucida Grande", "Lucida Sans Unicode", "Verdana", "Helvetica", "Arial", "sans-serif";
        }
  a { color: white}
  a:hover {
      font-size: 1.2em
  }
  ul { list-style-type: none}

  </style>
</head>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Travlr</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/places/edit.html.erb
<%= render "layouts/header" %>

<center><h1>TRAVLR</h1>
<body>
<h3>Edit your adventure!</h3>

<%= form_for @place, url: {action: "update"} do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>
<br>
<%= f.label :memory %>
<%= f.text_field :memory %>
<br>
<br>
<%= f.submit "Change" %>
<% end %>

<%= render 'layouts/footer' %>
</body>

app/views/places/new.html.erb
<%= render "layouts/header" %>

<center><h1>TRAVLR.</h1>
<body>
  <h3>Add an adventure and your favorite memory!</h3>

  <%= form_for @place, url: {action: "create"} do |f| %>

  <%= f.hidden_field :trip_id %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <br>
  <%= f.label :memory %>
  <%= f.text_field :memory, :size => 100 %>
  <br>
  <br>
  <%= f.submit "Create" %>
  <% end %>

<%= render 'layouts/footer' %>
</body>

app/views/places/show.html.erb
<%= render "layouts/header" %>

<center><h1>TRAVLR.</h1>
  <br>
<body>
  <% if flash[:success] %>
  <p style="color: green;"><%= flash[:success] %></p>
<% end %>
<p><%= @place.name %>- <%= @place.memory %></p>
<br>
<%= link_to "Load Comments", place_comments_path(@place), :class => "load_comments" %><br>
<br>

<%= form_for(@comment, :url => place_comments_path(@place)) do |f| %>
  <%= f.text_area :description %>
  <p><%= f.text_area :name %></p>
  <p><%= f.submit "Submit Comment", class: 'form-submit' %></p>
<% end %>

<br>

<div class="comments">
  <ul>

  </ul>
</div>

<%= link_to "Edit", edit_trip_place_path(@place) %>
<%= link_to "Delete", trip_place_path(:trip_id , @place), method: :delete %>
<br>
<%= render 'layouts/footer' %>
</body>

app/views/trips/_trip.html.erb
<div class="trip">
<h2> <%= link_to trip.name, trip_path(trip) %>-<%= trip.date %></h2>

<h4>-<%= trip.user.username.titleize%> </h4>
</div>

app/views/trips/edit.html.erb
<%= render "layouts/header" %>
<center><h1>TRAVLR</h1>

<body>
<h3>Edit this trip!</h3>

<%= form_for @trip, url: {action: "update"} do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>
<br>
<%= f.label :year %>
<%= f.text_field :date %>
<br>
<br>
<%= f.submit "Change" %>
<% end %>

<%= render 'layouts/footer' %>
</body>

app/views/trips/index.html.erb
<%= render "layouts/header" %>
<center><h1>TRAVLR.</h1>
<% @trips.each do |trip| %>
  <%= render partial: "trip", locals: {trip: trip} %>
  <% end %>

<script type="text/javascript" charset="utf-8">
$(function () {
  $(".js-more").on('click', function() {
    // get the id from the data attribute
    var id = $(this).data("id");
    $.get("/trips/" + id + "/detail", function(data) {
      alert(data);
    });
  });
});
</script>

app/views/trips/new.html.erb
<%= render "layouts/header" %>

<center><h1>TRAVLR.</h1>
<body>
    <h2>Add a trip!</h2>

    <%= form_for(@trip , action: "create") do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <br>
    <%= f.label :year %>
    <%= f.text_field :date %>
    <br>
    <br>
    <h2>While you are creating a trip, add an adventure!</h2>
    <p> Call it whatever you like: the name of a city, a date, or simply "Day 1".</p>
    <%= f.fields_for :places do |p| %>
      <%= p.label :Adventure %>
      <%= p.text_field :name %><br>
      <br>
      <%= p.label :memory %>
      <%= p.text_field :memory, :size => 100 %><br>
      <br>

    <% end %>
    <br>
    <%= f.submit "Create" %>
  <% end %>
</body>

app/views/trips/show.html.erb
<%= render "layouts/header" %>

<center><h1>TRAVLR.</h1>
<body>
  <% if flash[:success] %>
    <p style="color: yellow;"><%= flash[:success] %></p>
  <% end %>

  <h2 class="tripInfo"><%= @trip.name %>- <%= @trip.date %></h2>
  <%= link_to "Edit", edit_user_trip_path(@trip) %>
  <%= link_to "Delete", user_trip_path(current_user, @trip), method: :delete %><br>
  <h3>There were <%= @trip.places.count %> adventure(s) on this trip!</h3>
  <br>

  <% @trip.places.each do |place| %>
  <h3 class="placeInfo"><%=link_to place.name, trip_place_path(@trip, place) %></h3>
  <% end %>

  <%= link_to "Previous", trip_path(@trip.previous), :class => "previous_link", :"data-attribute" => @trip.id %>
  <%= link_to "Next", trip_path(@trip.next), :class => "next_link", :"data-attribute" => @trip.id  %>

  <br><br>

  <%= link_to "Add Adventure", new_trip_place_path(@trip, @place) %>
  <br>

  <%= render 'layouts/footer' %>
</body>

app/views/users/index.html.erb
<%= render "layouts/header" %>

<center><h1>TRAVLR.</h1>
  <h3>Travlr's most travelled!</h3>
   <% User.number_of_trips.each.with_index(1) do |user, index| %>
    <p> <%= index %>.<%= user.username.capitalize %> - <%= user.trips.count %> trips!</p>
     <% end %>
  <br>

<br>
  <%= render "layouts/footer" %>

app/views/users/new.html.erb
<%= render "layouts/header" %>

<center><h1>TRAVLR.</h1>
<body>
  <%= form_for @user do |f| %>

  <%= render 'layouts/error_messages', object: f.object %>


  <%= f.label :username %>
  <%= f.text_field :username %>
  <br>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>
  <br>
  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation %>
  <br>
  <br>
  <%= f.submit "Create my account" %>

<% end %>
</body>

app/views/users/show.html.erb
<%= render "layouts/header" %>

<center><h1>TRAVLR.</h1>
<br>
<body>
  <h2>Welcome, <%= @user.username.titleize %>!</h2>
  <% if flash[:success] %>
    <p style="color: green;"><%= flash[:success] %></p>
  <% end %>
  <h3>Your <%= @user.trips.count %> trip(s):</h3>
  <% @user.trips.each do |trip| %>
  <h3><%=link_to trip.name, user_trip_path(@user, trip) %>-<%= trip.date %></h3>
  <% end %>

  <br>
  <%= link_to 'Add Trip', new_user_trip_path(@user, @trip) %><br>
  <br>
  <%= link_to "Travlr's Most Travelled", users_path(@users) %>
  <br>
  <%= render 'layouts/footer' %>
</body>

app/views/users/welcome.html.erb
Hello World